### ISSUE TITLE
想问下keras的版本是什么

### ISSUE THREAD

**Issue by SefaZeng** [GlassyWing/bi-lstm-crf#2]
from keras_preprocessing.text import tokenizer_from_json
这里报错，keras的文档里面好像也没有这个

**Comment by GlassyWing** [comment]
keras 版本为2.2.4

**Comment by SefaZeng** [comment]
那还请问一下 开发集是另外的数据集吗 还是直接在训练集里面划分的？

**Comment by GlassyWing** [comment]
直接从训练集划分即可

**Comment by SefaZeng** [comment]
这样训练相当于每个epoch用了64000个样本 然后整个数据分在不同的epoch里面吗？为什么不把数据放在一个epoch里面呢？

**Comment by GlassyWing** [comment]
因为机器性能原因，要尽快看到效果，故意下调了。此外，由于数据集较大，调小一点并不影响训练效果

**Comment by trzhang-ai** [comment]
我使用Keras 2.2.4，跑python3 train_example.py会报错TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'。

**Comment by GlassyWing** [comment]
这是tensorflow版本的原因，tensorflow 版本为1.9.0

**Comment by trzhang-ai** [comment]
谢谢回复，我明天试试。
