### ISSUE TITLE
生成字典出错

### ISSUE THREAD

**Issue by trzhang-ai** [GlassyWing/bi-lstm-crf#3]
我在examples文件夹下新建了一个data文件夹，把生成的BIS文件放到里面。然后跑了python dict_test.py报错说文件找不到，我认为可能是由于路径有错所导致，我把dict_test.py里面../data/2014改写成data，这个错误就没有了但是又有ValueError: not enough value to unpack (expected 2, got 1)，原因是dltokenizer/tools.py第13行chars, tags = line.split(sent_delimiter)等号左边要两个值而等号右边只生成了一个值。这是一个BUG吗？还是其他什么原因? BI-LSTM-CRF还在持续更新吗？谢谢！

**Comment by GlassyWing** [comment]
项目已调整，请更新项目，按照readme中的数据处理方式进行处理
